version: 2.1

jobs:
  test:
    docker:
      - image: silex/emacs:master-ci
    steps:
      - checkout

      - run:
          name: Run tests
          command: emacs -Q -batch -l ert -L test/ -l test/test-helper.el -l test/all-tests.el -f ert-run-tests-batch-and-exit

workflows:
  test:
    jobs:
      - test
