version: 2.1

jobs:
  test:
    docker:
      - image: silex/emacs:master-ci
    steps:
      - checkout

      - run:
          name: Run tests
          command: make test

workflows:
  test:
    jobs:
      - test
