version: 2.1

jobs:
  test:
    docker:
      - image: silex/emacs:master-ci
    steps:
      - checkout

      - run:
          name: Run tests
          command: make test

      - restore_cache:
          keys:
          - v2-deps--{{ checksum "init.el" }}
          - v2-deps--

      - run:
          name: Test config initialization
          command: emacs --batch --load init.el

      - save_cache:
          paths:
            - ~/.emacs.d/elpa
          key: v2-deps--{{ checksum "init.el" }}

workflows:
  test:
    jobs:
      - test
